---
title: "PROYECTOR2019"
author: "CAMILLA MOSSEDDU"
date: "16/11/2019"
output: 
  html_document:
    toc: true
    theme: united
    toc_depth: 3

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Loading the rvest package
library('rvest')
library( tables ) # Presentación de tablas
library("ggplot2")
```





# Seccion 1

## Una sección en el que indiquen dos páginas con recursos sobre expresiones regulares discutidas (cuál es mejor, cuál es peor, por qué).

https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-spanish.pdf


# Seccion 2
## Una sección en la que se indiquen dos páginas con recursos sobre markdown y discutirlas como antes.

```{r}

#Specifying the url for desired website to be scraped
url <- 'https://www.milanuncios.com/coches-de-segunda-mano/'
#Reading the HTML code from the website
webpage <- read_html(url)
#find the listing nodes and id of each node
listings<-html_nodes(webpage, "div.aditem-detail")

#search each listing node for the child ticket and limit view criteria
precio_data<-sapply(listings, function(x) {html_node(x, ".aditem-price") %>% html_text()} ) 
kms_data<-sapply(listings, function(x) {html_node(x, ".kms.tag-mobile") %>% html_text()} ) 
ano_data<-sapply(listings, function(x) {html_node(x, ".ano.tag-mobile") %>% html_text()} ) 
die_data<-sapply(listings, function(x) {html_node(x, ".die.tag-mobile") %>% html_text()} ) 
gas_data<-sapply(listings, function(x) {html_node(x, ".gas.tag-mobile") %>% html_text()} ) 
cc_data<-sapply(listings, function(x) {html_node(x, ".cc.tag-mobile") %>% html_text()} )
puertas_data<-sapply(listings, function(x) {html_node(x, ".ejes.tag-mobile") %>% html_text()} )
```






```{r}
# crear dataframe de vectores
coches_df <- data.frame(precio_data,
                           kms_data,
                            ano_data,
                           die_data,gas_data,cc_data,puertas_data)

#combinamos las variables de diesel y gasolina en una misma columna
coches_df$combustible<-NA
coches_df$combustible[which(!is.na(coches_df$gas_data))]<-as.character(coches_df$gas_data[which(!is.na(coches_df$gas_data))])
coches_df$combustible[which(!is.na(coches_df$die_data))]<-as.character(coches_df$die_data[which(!is.na(coches_df$die_data))])

#eliminamos las columnas de diesel y gasolina
coches_df <- subset(coches_df, select = 
      c(precio_data,kms_data,ano_data,cc_data,puertas_data,combustible))
```

#coches_df<-na.omit(coches_df)
```{r}
coches_df$ano_data <- gsub("año ", "", coches_df$ano_data)
coches_df$kms_data<- gsub(" kms", "", coches_df$kms_data)
coches_df$cc_data<- gsub(" cv", "", coches_df$cc_data)
coches_df$puertas_data<- gsub(" puertas", "", coches_df$puertas_data)
coches_df$precio_data<- gsub("€", "", coches_df$precio_data)
```




#Hacemos un plot entre el precio y los caballos.
```{r}
ggplot(data = coches_df, mapping = aes(x = as.numeric(cc_data), y = as.numeric(precio_data), colour = ano_data)) +
  geom_point()
```


```{r}
ggplot(coches_df, aes(ano_data)) + geom_bar(fill='darkblue',color="darkred")  

{r eval=FALSE, include=FALSE}
ggplot(coches_df, aes(x = puertas_data, y = precio_data)) +
  geom_point() + geom_smooth() + 
  facet_grid(~combustible)
```


```{r}
Salaries <- read.csv("C:/Users/50051120/Desktop/Clases R/PracticaCamilla/Salaries.csv")
```


```{r}
#https://ggplot2.tidyverse.org/reference/ggtheme.html
p1 <- ggplot(coches_df) +
  geom_point(aes(x = as.numeric(cc_data), y = as.numeric(precio_data), colour = combustible)) +
  labs(title = "Precio VS Caballos",
       subtitle = "Datos de coches",
       caption = "Datos de Milanuncios",
       tag = "Figure 1",
       x = "Caballos",
       y = "Precio",
       colour = "Combustible")
p1 + theme_dark()
```



```{r}
#https://cran.r-project.org/web/packages/expss/vignettes/tables-with-labels.html
library(expss)
Salaries = apply_labels(coches_df,
                      precio_data = "Precio",
                      combustible = "Combustible",
                      ano_data = "Año",
                      kms_data = "Kilometros",
                      puertas_data = "Puertas",
                      cc_data = "Caballos"
)
cro(coches_df$precio_data, coches_df$puertas_data)
```


```{r}
cro_cpct(coches_df$ano_data, list(total(), coches_df$combustible, coches_df$puertas_data))
```
